### ISSUE TITLE
a few more links

### ISSUE THREAD

**Issue by rodneyrehm** [prettydiff/a11y-tools#3]
informational
- [html5accessibility.com](http://html5accessibility.com/) audits browser compatibility

tools
- [Keyboard Event Viewer](http://w3c.github.io/uievents/tools/key-event-viewer.html) is a tool maintained by/for the W3C UI Events and a _bit_ more detailed than wesbos/keycodes.
- [outline-audit](https://github.com/edenspiekermann/outline-audit) analyzes the document outline (headline structure)
- [Dyslexia simulator](http://geon.github.io/programming/2016/03/03/dsxyliea) makes you appreciate not suffering from dyslexia…

libraries
- [ally.js](http://allyjs.io/) is a JS library dealing with focus management
- [a11y.js](https://github.com/IBM-Watson/a11y.js) is a JS library simplifying working with aria attributes in the DOM

services
- [tenon.io](http://tenon.io/) API to test documents against WCAG
- [CaptionBot](https://www.captionbot.ai/) translates images to text

widgets
- [edenspiekermann/a11y-dialog](https://github.com/edenspiekermann/a11y-dialog)
- [edenspiekermann/a11y-toggle](https://github.com/edenspiekermann/a11y-toggle)

**Comment by prettydiff** [comment]
Thank you very much for the contribution!
